### ISSUE TITLE
[BUG] Alien removal is done at the very end of preprocessing

### ISSUE THREAD

**Issue by DSimonne** [carnisj/bcdi#284]
Hi,

I'm not sure if it's a bog but I noticed that the alien removal is performed at the end of preprocessing, after the centering and the determination of q.

So it's quite problematic when there are aliens in the peak, because the centering is off.

**Comment by carnisj** [comment]
You are right, and there are several reasons for that:
- one should in principle not interpolate the data in preprocessing
- but when that happens, you want the interpolation to be precise. If aliens are removed before the interpolation, there are actually more pixels (artefacts) that needs to be masked
- the corrected detector angles are needed for the interpolation using the transformation matrix

So this explains the rational behind this design. Another thing is that if we try to find a peak after masking, the centering might be off as well because we change photon statistics (especially when the SNR is low, the impact of the (masked) background is larger). So I'm not sure if masking before centering would be more efficient or generic.

For cases where centering fails, there is still the parameter `bragg_peak` in the config to set it manually, as a backup solution.

**Comment by carnisj** [comment]
Modifying this part would require a complete rewrite of the script, I'm not convinced that this is worth and there is already a workaround. Therefore, I'll close this issue.
