### ISSUE TITLE
wrap / unwrap in strain.py

### ISSUE THREAD

**Issue by sjleake** [carnisj/bcdi#5]
Hi Jerome,
I am revisiting some scripts from last year and I noticed strain.py has changed quite a bit. Do you remember how you modified wrap to become unwrap. 
It is not as effective as it was in the past, i.e. artefacts from problems unwrapping.
Thanks

**Comment by sjleake** [comment]
it is ok I understand how it has been done in strain.py the extent_phase value was completely off dure to the choice of support_threshold, I must have just been very lucky the first time!

**Comment by carnisj** [comment]
Hi Steven,
I hope that you are doing well. Yes, often the function itself behaves as it should but the input is wrong because of bad thresholding or similar. Unfortunately, there are a lot of parameters and assumptions that should be checked for every different dataset. I think that Bragg CDI will remain a technique for experts for still quite some time.
About phase unwrapping, you probably are aware that this is not a 1 to 1 problem, there is an infinity of solutions and we are looking for one of them. For normal quality data, it seems to work relatively well.
Best,
Jerome
    Le jeudi 9 avril 2020 à 10:02:01 UTC+2, sjleake <notifications@github.com> a écrit :  
 
 


it is ok I understand how it has been done in strain.py the extent_phase value was completely off dure to the choice of support_threshold, I must have just been very lucky the first time!
