### ISSUE TITLE
[FEAT] Add a preview for Documentation

### ISSUE THREAD

**Issue by kadatatlukishore** [carnisj/bcdi#72]
**Is your feature request related to a problem? Please describe.**
I've updated the documentation recently. It will be useful to have a Github action which can show the preview of the documentation.
Like this: 

https://vercel.com/gmt/pygmt/EciYUVhpbBkBsrAUDMdCnSx1hPey   
Preview sample - https://pygmt-lf7wq45kr-gmt.vercel.app/

**Describe the solution you'd like**

You can follow this - 
- https://github.com/GenericMappingTools/pygmt/blob/master/.github/workflows/ci_docs.yml
-   You can check the Github actions working here, 
     - https://github.com/GenericMappingTools/pygmt/pull/1390

**Comment by carnisj** [comment]
It sounds good, I was also looking for such tool. There are two things here: (i) checking if the doc builds correctly, this can be done with twine check (could be easily added as a task in dodo.py), and (ii) visualizing the doc itself. I will have a look at the links thanks.

**Comment by kadatatlukishore** [comment]
Glad it helps.

**Comment by carnisj** [comment]
I had a look at it, but it seems a bit overkilling for the purpose, plus GitHub actions often fail just because of timeout. I decided for the option of building the HTML doc in the doit tasks. Then the contributor can check if this build correctly and visualize it before submitting a PR. Have a look at dodo.py.
